address: https://test-stand.gb.ru
browser: chrome
sleep_time: 3

username: Petrucha1
password: 966f0a27e0
token: 1be41c44d3a8e6dd28706a1b6ff47be6
email: Petrucha1@email.ru
err_login: test
err_pass: test
content: Three children, Jeanne, Vincent and, gathered in the attic of the house on Fontanka, made insidious plans to take over the whole world. The children grew up - the poor grew up. They've taken over the world. Each in his own way. And they began to play with him. But, it turned out, even peace is not enough if you can't get the love of someone who is nearby. Everything didn't go according to plan. After playing enough, they broke their toy.
